### ISSUE TITLE
realSFS on multiple regions

### ISSUE THREAD

**Issue by mlucenaperez** [mfumagalli/ngsTools#18] opened 2018-09-04 12:04 UTC
Can I use realSFS specifying more than one region? if the answer is yes, how? 

I am looking for the equivalent to -rf in ANGSD in NGSTools

The idea would be:

Estimate the SFS around SEVERAL REGIONS:
	-> ./realSFS afile.saf.idx -r $REGION_FILE

cat $REGION_FILE

chr1:1-10000
chr2:135000000-140000000 
chr3:4880-194598

**Comment by mfumagalli** [comment] 2018-09-04 12:31
Hi,

realSFS is part of ANGSD, not ngsTools, and you can specify multiple
regions in a file using the option -rf FILE
Check here: http://www.popgen.dk/angsd/index.php/Input#BAM_files

cheers

Matteo

**Comment by mlucenaperez** [comment] 2018-09-05 08:58
Thank you Matteo

realSFS is part of ANGSD:  Indeed! Sorry, my mistake. 

Anyway, using -rf was my first attempt and it is not working properly. That's why I asked, although not to the right person. 

Thank you anyway. 

`$NGSTOOLS/realSFS fst stats  $POP1.$POP2.unfolded-lr.fst.idx  -rf $REGIONFILE 
        -> Assuming idxname:c_ll_ya_n008.x_ll_ba_n003.unfolded-lr.fst.idx
        -> Assuming .fst.gz file: c_ll_ya_n008.x_ll_ba_n003.unfolded-lr.fst.gz
        -> Problem opening file: '-rf' 


head $REGIONFILE
lp23.s00003:31499-31526
lp23.s00003:31532-31588
lp23.s00003:31595-31989
lp23.s00003:32018-32405
lp23.s00003:32614-32937
lp23.s00021:1901737-1901737
lp23.s00021:1901802-1901802
`

**Comment by mfumagalli** [comment] 2018-09-05 09:15
the issue is that fst stats required 2 files in input (one per pop) and
thus it takes "-rf" as the name of the second file

also check the format for the regions file on angsd website

**Comment by mfumagalli** [comment] 2018-09-05 09:38
ah yes, sorry you are right; not sure what's happening; perhaps realSFS
does not work with -rf option and in this case you may have to generate
separate saf.idx files for each region

**Comment by mfumagalli** [comment] 2018-09-05 12:44
I close this issue as it's duplicated from ANGSD's github.

**Closed by mfumagalli** 2018-09-05 12:44 UTC
